# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 753d878bc145e5d7c9a9ef2b370b72c3907f68fa48c393e482f0d65937613a64fdd0cf703635e5e2c7186b4e07a6193c481747505923102cf50bb4a8ee172c66

test:
  secret_key_base: 209c048c3e9c094cc938a7b14a19db57bc9efdeac5489e73a6903017490cd381a2e166a162a61de5465ed0a75e252321b864b483d8929335fb101d4ab75e66e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
